### ISSUE TITLE
Improve rendering time in Unity

### ISSUE THREAD

**Issue by nlferman** [joshherkness/AR-Top#252]
Currently rendering each update can take 6-12 seconds. This could be frustrating for viewers and DMs if updates are frequent. We want to lower this as much as possible.
Two approaches:
1) Multi-thread in Unity so models can be rendered faster.
2) Handle only diffs in Unity so only a few blocks at a time are changed.

**Comment by jjrobertson14** [comment]
For approach 1, there's a huge problem, GameObjects and transforms can only be accessed in the main unity thread.

But, we can still improve the performance of a full map loading in these two ways:

1)
Don't have a GameObject for each voxel, but break the map grid into chunks (cubes of 64 voxels or something) that will be the game objects. Each chunk can store the vertices and colors of the voxels in it and render using that info. That *might* remove a noticeable amount of overhead from gameobject instantiations. But it seems like it may be too much effort for possibly improving the rendering time by a small amount.

2)
We can render the map and instantiate voxel gameobjects in a coroutine, and have it yield every so often, allowing the user to interact for a bit until the loading resumes. The rendering would take longer, but the app won't freeze up as badly because the user would be given time to interact while the loading is happening at regular intervals, and it might not even be noticeable to users.

But, might want to scrap both and just focus on the individual voxel updates.

**Comment by joshherkness** [comment]
Is this considered complete?

**Comment by nlferman** [comment]
This is done now.
